# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/nvme0n1p5";
      preLVM = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/mapper/vg-nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/424E-141B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # swapDevices = [
  #   { device = "/dev/disk/by-label/swap"; }
  # ];
  #
  # boot.resumeDevice = "/dev/disk/by-label/swap";

  boot.kernelParams = [
   "resume_offset=SWAP_OFFSET"
   "acpi_osi=Linux"
   "acpi_backlight=video"
   ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
